[package]
name = "station-plan"
version = "0.1.0"
edition = "2024"
authors = ["Richard M. Hamilton"]
description = "Field-station crew scheduling application"
repository = "https://github.com/rhamenator/StationPlan"

[package.metadata.wix]
upgrade-guid = "5E66C5EF-C8D2-480B-AA06-DC10A7297C7A"
path-guid = "A4C51FC8-9536-4D41-AE38-64AEEF58D86F"
license = false
eula = false

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
